geomet_weather/tileindex/elasticsearch_.py
changed elevation tileindex from integer to text so we can add values like 'surface' or 500mb
=> changed elevation tileindex from integer to text so we can add string

geomet_weather/store/redis_.py
Added a simple get method to RedisStore class to get the value of a given key from a Redis store.
=> added redis get method to RedisStore class

geomet_weather/layer/base.py
Added stored and tileindex plugin connections to BaseLayer class
=> added store and tileindex plugin connections to BaseLayer class

.gitignore
Added .idea to gitignore for those who use PyCharm IDE.
=> added .idea folder to .gitignore

geomet_weather/layer/model_gem_global.py
added the identfy function that uses a filepath and creates class properties
=> added the identify function

geomet_data_registry/store/redis_.py
Added a set method to the RedisStore object in order to easily set a key, value pair.
=> Redisstore set method

geomet_data_registry/layer/base.py
Added a simple register function to test writing to abstracted store and tileindex.
=> added register function for BaseLayer object

geomet-data-registry.env, geomet_data_registry/__init__.py, geomet_data_registry/env.py, geomet_data_registry/layer/__init__.py, geomet_data_registry/log.py, geomet_data_registry/tileindex/elasticsearch_.py, geomet_data_registry/util.py, requirements.txt
- add logging
- update ES workflow to support ES 7
- add JSON pretty printing helper function
=> Logging es deps

geomet_data_registry/layer/base.py, geomet_data_registry/layer/model_gem_global.py, geomet_data_registry/tileindex/base.py, geomet_data_registry/tileindex/elasticsearch_.py, geomet_data_registry/trigger/core.py
Initial time stamping of important steps in the data registration process (file creation, reception, identification, registration).
=> First pass at timestamping important registration steps

README.md, geomet-data-registry.env, geomet_data_registry/env.py, geomet_data_registry/layer/radar_1km.py, geomet_data_registry/store/__init__.py, geomet_data_registry/store/base.py, geomet_data_registry/store/redis_.py, geomet_data_registry/tileindex/__init__.py, geomet_data_registry/tileindex/base.py, geomet_data_registry/tileindex/elasticsearch_.py, geomet_data_registry/trigger/core.py
- update Docker setup
- rename create/delete to setup/teardown of tileindex and store services
- added `update` and `update_by_query` stubs to `geomet_data_registry.layer.base`
- fixed registration/update idempotence issues
- flake8 fixes
=> update tileindex/store services workflow, update base class stubs, fix registration idempotence issues, flake8

geomet_data_registry/handler/core.py, geomet_data_registry/layer/cansips.py, geomet_data_registry/plugin.py, requirements.txt
add initial handler for cansips
=> add initial handler for cansips

geomet_data_registry/layer/base.py, geomet_data_registry/layer/model_gem_global.py
we changed the yaml configuration for GDPS so we had to update the layer handler.
=> update gdps for new configuration in yaml

README.md, geomet_data_registry/store/__init__.py, geomet_data_registry/store/base.py
Added the ability to add a yaml file or key/value combination in redis from the geomet-data-registry repo.
=> update redis set function

geomet_data_registry/store/__init__.py, geomet_data_registry/store/base.py, geomet_data_registry/store/redis_.py
updated set and get function in store to set_key and get_key
=> updated set and get function in store to set_key and get_key

conf/cansips.yml, conf/model_gem_global.yml, conf/radar.yml, conf/reps.yml
Added a REPS conf sample and fixed typos in existing conf files for other models.
=> added sample REPS configuration and typo fixes in other sample confs

geomet_data_registry/store/__init__.py
Added the `geomet-data-registry store get -k <key_name>` command to the geomet-data-registry CLI.
=> Added a get command for store via cli

geomet_data_registry/layer/base.py, geomet_data_registry/layer/cansips.py, geomet_data_registry/layer/model_gem_global.py, geomet_data_registry/layer/radar_1km.py, geomet_data_registry/layer/reps.py
This is related to a previous merge request where we changed the store function from get --> get_key and set --> set_key
The code in the layer script weren't updated yet.
=> fixed store get to get_key

geomet_data_registry/tileindex/elasticsearch_.py
proposed fix for localhost with port in netloc
=> proposed fix for localhost with port in netloc

geomet_data_registry/layer/base.py, geomet_data_registry/layer/cansips.py, geomet_data_registry/layer/model_gem_global.py, geomet_data_registry/layer/radar_1km.py, geomet_data_registry/layer/reps.py
added LayerError from base when the layer is not in the configuration file
=> added LayerError when the layer is not in the configuration file

geomet_data_registry/layer/base.py, geomet_data_registry/layer/cansips.py, geomet_data_registry/layer/model_gem_global.py, geomet_data_registry/layer/radar_1km.py, geomet_data_registry/layer/reps.py, geomet_data_registry/tileindex/elasticsearch_.py
added the model column in the tileindex and updaet CanSIPS forecast hour interval.
=> added 'model' column in th tileindex

geomet_data_registry/layer/base.py, geomet_data_registry/tileindex/base.py, geomet_data_registry/tileindex/elasticsearch_.py
added support for bulk insert in ES when there are more then one band per file.
=> added bulk support for multi-band files

geomet_data_registry/layer/model_gem_global.py
fixed max range issue for gdps which caused the latest forecast hour to fail
=> fixed max range issue for gdps

geomet_data_registry/layer/reps.py
added function for time keywords for reps
Only needed to modify the add_time_keys function in the layer/reps.py handler.
=> added function for time keywords for reps

README.md, geomet_data_registry/layer/model_gem_global.py, geomet_data_registry/layer/model_hrdps_continental.py, geomet_data_registry/store/__init__.py, geomet_data_registry/store/base.py, geomet_data_registry/store/redis_.py, geomet_data_registry/util.py
This PR adds store key listing workflow with optional functionality to filter based on a regular expression.
Other minor updates:
- fix flake8 errors
- in CLI examples, add `=` to long options
=> add store list keys workflow

geomet_data_registry/handler/core.py, geomet_data_registry/layer/model_gem_regional.py, geomet_data_registry/plugin.py
This MR adds an initial RDPS layer handler.
It has been tested and verified in my local dev environment against RDPS data pulled from DataMart with wget.
Also in this MR:
- Small fix to the HRDPS layer handler docstring.
=> initial rdps layer handler

conf/model_giops.yml, conf/sarracenia/model_giops.conf, geomet_data_registry/handler/core.py, geomet_data_registry/layer/model_giops.py, geomet_data_registry/plugin.py
This PR contains the initial configuration files and layer handler for GIOPS 2D and 3D data.
The handler was tested with several entire model runs pulled from the DataMart and no issues were detected.
Also in this PR are small PEP8 fixes for inline comment spacing in the REPS handler.
=> Add GIOPS yaml configuration

conf/reps.yml, geomet_data_registry/layer/reps.py
rmv vrt creation for single band referencing
also make sure the bands number are 2 digits (01 instead 1)
=> rmv vrt creation for single band referencing

conf/reps.yml
A few small errors slipped into our REPS yaml configuration.
This PR fixes those errors (missing layers, wrong files expected count, etc.)
=> Fix several errors in RDPS yaml configuration

conf/geps.yml
Fixes some small errors in the GEPS yml configuration file.
=> fixed errors in GEPS yml configuration

conf/cgsl.yml, conf/sarracenia/cgsl.conf, geomet_data_registry/handler/core.py, geomet_data_registry/layer/cgsl.py, geomet_data_registry/plugin.py
This PR contains the intial sarra and yaml configuration files for CGSL (Coupled Gulf of Saint Lawrence regional model) as well as its layer handler.
Tested and validated with a full data pull from the DataMart on my local build.
=> intial cgsl configuration and layer handler

geomet_data_registry/layer/cgsl.py, geomet_data_registry/layer/geps.py, geomet_data_registry/layer/model_gem_global.py, geomet_data_registry/layer/model_gem_regional.py, geomet_data_registry/layer/model_giops.py, geomet_data_registry/layer/model_hrdps_continental.py, geomet_data_registry/layer/reps.py, geomet_data_registry/plugin.py, geomet_data_registry/store/redis_.py
Flake8 fixes for entire repository.
=> flake8 fixes

conf/rdwps.yml, conf/sarracenia/rdwps.conf, conf/sarracenia/rdwps_gulf.conf, geomet_data_registry/handler/core.py, geomet_data_registry/layer/rdwps.py, geomet_data_registry/plugin.py
This PR implements the initial layer handler, model configuration yml, and sarracenia configuration file for the RDWPS model.
=> Inital RDWPS layer handler and config

conf/gdwps.yml, conf/sarracenia/gdwps.conf, geomet_data_registry/handler/core.py, geomet_data_registry/layer/gdwps.py, geomet_data_registry/plugin.py
This PR implements the initial layer handler, model configuration yml, and sarracenia configuration file for the GDWPS model.
=> initial gdwps config and handler

conf/sarracenia/wcps.conf, conf/wcps.yml, geomet_data_registry/handler/core.py, geomet_data_registry/layer/wcps.py, geomet_data_registry/plugin.py
Initial WCPS layer handler, yaml configuration, and sarracenia configuration.
Tested with a complete model run pulled from DD this morning.
=> Initial wcps layer handler and config

conf/hrdpa.yml, conf/sarracenia/hrdpa.conf, geomet_data_registry/handler/core.py, geomet_data_registry/layer/hrdpa.py, geomet_data_registry/plugin.py
Initial HRDPA layer handler and config.
Test against a a complete data pull from https://dd.weather.gc.ca/analysis/precip/hrdpa/ with no issues found.
=> initial hrdpa layer handler and config

conf/rdpa.yml, geomet_data_registry/handler/core.py, geomet_data_registry/layer/base.py, geomet_data_registry/layer/cansips.py, geomet_data_registry/layer/cgsl.py, geomet_data_registry/layer/gdwps.py, geomet_data_registry/layer/geps.py, geomet_data_registry/layer/hrdpa.py, geomet_data_registry/layer/model_gem_global.py, geomet_data_registry/layer/model_gem_regional.py, geomet_data_registry/layer/model_giops.py, geomet_data_registry/layer/model_hrdps_continental.py, geomet_data_registry/layer/radar_1km.py, geomet_data_registry/layer/rdpa.py, geomet_data_registry/layer/rdwps.py, geomet_data_registry/layer/reps.py, geomet_data_registry/plugin.py, geomet_data_registry/tileindex/elasticsearch_.py
Initial RDPA layer handler (supports both archived 15KM resolution data and 10km resolution data) and configuration.
Tested against both recent data available on DD and with our archived 15km data.
Also in this PR, project-wide flake8 fixes(removal of a ton of `# noqa` comments!) and the removal of some logger messages that slipped by in my previous HRDPA pull request (sorry!).
=> initial rdpa layer handler and config and flake8 fixes

conf/cansips.yml, geomet_data_registry/layer/cansips.py
merge request for cansips.
we need a add_time_key function here because the interval is in months and thus require a another function then timedelta for datetime manipulation.
=> updated on cansips

conf/data-feed-cleanups.cron
Adds an initial data feed cleanup cron.
=> add initial data feed cleanup cron

conf/data-feed-cleanups.cron
Updates the cron file to include data ingested by the most recent loaders.
=> update data cleanup crons for new loaders

README.md, conf/sarracenia/cansips.conf, conf/sarracenia/cgsl.conf, conf/sarracenia/gdwps.conf, conf/sarracenia/geps.conf, conf/sarracenia/hrdpa.conf, conf/sarracenia/model_gem_global.conf, conf/sarracenia/model_gem_regional.conf, conf/sarracenia/model_giops.conf, conf/sarracenia/model_hrdps_continental.conf, conf/sarracenia/rdwps.conf, conf/sarracenia/rdwps_gulf.conf, conf/sarracenia/reps.conf, conf/sarracenia/wcps.conf, deploy/default/sarracenia/dd.weather.gc.ca.conf, geomet-data-registry.env, geomet_data_registry/env.py, geomet_data_registry/layer/base.py, geomet_data_registry/layer/geps.py, geomet_data_registry/layer/hrdpa.py, geomet_data_registry/layer/model_giops.py, geomet_data_registry/layer/rdpa.py, geomet_data_registry/layer/rdwps.py, geomet_data_registry/tileindex/elasticsearch_.py
This PR applies environment variables to handle MetPX value.  Also included is a flake8 sweep and addition of a `url` property to the ES tileindex mappings (N.B. code still needs to be updated to manage the new `url` property).
=> add environment variables, fix flake8

conf/model_raqdps-fw.yml, conf/model_raqdps.yml, conf/sarracenia/model_raqdps-fw.conf, conf/sarracenia/model_raqdps.conf, geomet_data_registry/handler/core.py, geomet_data_registry/layer/model_raqdps-fw.py, geomet_data_registry/layer/model_raqdps.py, geomet_data_registry/plugin.py
Adds RAQDPS and RAQDPS-FW configurations and handlers.
@RousseauLambertLP, this should be a good starting point for incorporating the related cumulative effects data.
Tested with several complete model runs for both models.
=> add raqdps configs and handlers

deploy/default/sarracenia/radar.conf
updated radar sarracenia config for fluxi
CC @Dukestep
=> updated radar sarracenia config for fluxi

geomet_data_registry/layer/radar_1km.py
Fixes minor typo in radar loader.
=> fix typo in radar loader

deploy/default/sarracenia/cansips.conf, deploy/default/sarracenia/cgsl.conf, deploy/default/sarracenia/gdwps.conf, deploy/default/sarracenia/geps.conf, deploy/default/sarracenia/hrdpa.conf, deploy/default/sarracenia/model_gem_global.conf, deploy/default/sarracenia/model_gem_regional.conf, deploy/default/sarracenia/model_giops.conf, deploy/default/sarracenia/model_hrdps_continental.conf, deploy/default/sarracenia/model_raqdps-fw.conf, deploy/default/sarracenia/model_raqdps.conf, deploy/default/sarracenia/rdwps.conf, deploy/default/sarracenia/rdwps_gulf.conf, deploy/default/sarracenia/reps.conf, deploy/default/sarracenia/wcps.conf, geomet-data-registry.env, geomet_data_registry/event.py, geomet_data_registry/layer/base.py, geomet_data_registry/tileindex/elasticsearch_.py
update sara conf for notification only and remove file_creation_datetime
Cansips needs to be kept on disk because we serve the archive in geomet
=> update sara conf for notification only and remove file_creation_datetime

deploy/default/model_raqdps-fw-ce.yml, deploy/default/model_raqdps.yml, deploy/default/model_rdaqa-ce.yml, deploy/default/sarracenia/model_raqdps-fw-ce.conf, deploy/default/sarracenia/model_rdaqa-ce.conf, geomet-data-registry.env, geomet_data_registry/layer/model_raqdps-fw-ce.py, geomet_data_registry/layer/model_raqdps-fw.py, geomet_data_registry/layer/model_rdaqa-ce.py, geomet_data_registry/plugin.py, geomet_data_registry/util.py
Initial RAQDPS-FW Cumulative Effects and RDAQA Cumulative Effects loaders. Some additional cleanup of the RAQDPS-FW (non Cumulative Effects) loader is also included.
Loaders have both been tested on local instance against their own complete set of data.
=> Initial raqdps-fw/rdaqa cumulative effects loaders and config

deploy/default/model_gem_regional.yml, deploy/default/reps.yml, geomet_data_registry/plugin.py
* Fixed file pattern in plugin.py
* Added 2 new model runs for reps
* fixed forecasthours error in the RDPS configuration
=> update conf for GDR

deploy/default/sarracenia/rdpa.conf
added rdpa sarracenia conf file for triggers
=> added rdpa sarracenia conf file

Makefile, docker/docker-compose.yml
I have added all the configuration we have to the Makefile and update the docker-compose.yml file for ES configuration for a single node.
=> update Makefile and docker compose

deploy/default/model_raqdps.yml, deploy/default/radar.yml, geomet_data_registry/layer/model_giops.py, geomet_data_registry/layer/model_riops.py, geomet_data_registry/layer/radar_1km.py
fix minor incoherence in code
Unused variable
Missing parameter
Missing dimension in yml
make member and geomet_layer plurial for consistency with other conf
Thanks to @PhilippeTh for identifying these issues.
=> fix minor incoherence in code

geomet_data_registry/layer/rdpa.py
fixed logic error in rdpa
We were creating 2 features in ES instead of the one needed.
Thanks to @PhilippeTh for pointing out the issue
=> fixed logic error in rdpa

deploy/default/gdwps.yml, deploy/default/model_giops.yml, deploy/default/model_raqdps-fw.yml, deploy/default/model_raqdps.yml, deploy/default/radar.yml, deploy/default/rdwps.yml, deploy/default/sarracenia/gdwps.conf, deploy/default/sarracenia/radar.conf, deploy/default/sarracenia/rdwps.conf, geomet_data_registry/layer/gdwps.py, geomet_data_registry/layer/model_giops.py, geomet_data_registry/layer/model_raqdps.py, geomet_data_registry/layer/model_raqdps_fw.py, geomet_data_registry/layer/radar_1km.py, geomet_data_registry/layer/rdwps.py, geomet_data_registry/plugin.py, geomet_data_registry/util.py
Updates Radar, GDWPS, RDWPS, RAQDPS, and RAQDPS-FW configuration and layer handlers to adhere to recent filename changes and other upstream modifications to the data.
Tested against model runs available on `dd.weather.gc.ca` and `dd.alpha.weather.gc.ca` for GDWPS, RDWPS, RAQDPS and RAQDPS-FW. Radar was tested against local files.
=> update layer config/handlers for new filenames and IC3 changes
