ECCC-MSC/geomet-data-registry

geomet_weather/trigger/event.py

I noticed a few issues with event.py when I tried getting it to work with sarracenia.
I modified the import statement to reflect the current project structure (it was previously importing from `msc_pygeoapi.trigger`) and moved the import statement into the dispatch method. When trying to start the sr_subscribe with the import statement at the Event class level, sarracenia was complaining with the following message in the log:
`2019-06-21 11:52:42,802 [WARNING] name 'BaseTriggerHandler' is not defined`
Moving it into the try block of the dispatch method resolves this issue. I believe this is related to [import issues in sarracenia](https://github.com/MetPX/sarracenia/blob/master/doc/Prog.rst#why-doesn-t-import-work).
We were also missing the `self` argument when creating the Event() …

Moved BaseTriggerHandler import into dispatch method and fixed Event() instantiation

---

geomet_data_registry/tileindex/elasticsearch_.py

Fixes issue where all items' `register_datetime` property value were update due to the `query` key not being passed on correctly to the `es_query_body` variable.
As reported in #19 .
This fix was tested using the `add-file` flag with the CLI tool on two separate data files each of which conserved its own `register_datetime` value when updated.

fixed query dictionary creation used to create the query key in es_body_query

---

geomet_data_registry/handler/core.py
geomet_data_registry/layer/cansips.py
geomet_data_registry/layer/reps.py
geomet_data_registry/plugin.py
geomet_data_registry/tileindex/elasticsearch_.py

Initial commit for the REPS handler. I've tested it with both REPS products and members via the CLI.
Another change in this MR is the way we do the update_by_query in ES. We previously used a `match` query to match the entire filename in order to update the register_datetime property of a entry in ES. This has been changed to `wildcard` query  in order to capture cases where the filepath contains the entire VRT XML. The wildcard query returns documents in the ES index that *contain* the filepath in the document's file property. I have tested this change with both the GDPS handler and the REPS handler. Would like to know your thoughts on a better approach if there is one!

Added intial REPS layer handler, changed ES update_by_query to wildcard to allow for VRT stored in filepath

---

geomet_data_registry/store/__init__.py

Added a graceful error for when no flags were passed to `geomet-data-registry store set` instead of producing a `TypeError` if no flags were given.

Added graceful error for when no key or config file passed to store set command

---

geomet_data_registry/tileindex/elasticsearch_.py

2 fixes
1. `if self.url_parsed.path is not None:` removed the None as this is an empty string if value is not present.
2. changed `self.connection` to `self.es` because that's the variable used in the rest of the code.
CC @Dukestep

updated a variable name to be able to connect to ES

---

geomet_data_registry/layer/radar_1km.py

Fixes issue #42.
We weren't setting `self.filepath` in the RADAR handler and so when updating the document in ES to add the `register_datetime` property, self.filepath was `None`.
Example of erroneous query:
```
{'query': {'wildcard': {'properties.filepath.raw': {'wildcard': '*None*'}}}, 'script': {'source': 'ctx._source.properties.register_datetime = "2019-09-26T13:06:08.995528"'}}
```
This sets the self.filepath variable in the radar layer handler and populates the query_dict with the right filepath.
Query after fix:
```
{'query': {'wildcard': {'properties.filepath.raw': {'wildcard': '*/data-san/geomet/feeds/local/RADAR/1KM/MMHR/201909261150_RADAR_COMPOSITE_1KM_MMHR.tif*'}}}, 'script': {'source': 'ctx._source.properties.register_datetime = "2019-09-26T13:15:45.574624"'}}
```

Added missing self.filepath variable

---

geomet_data_registry/handler/core.py
geomet_data_registry/tileindex/elasticsearch_.py

Adds an ES ingest pipeline to calculate file registration on the Elasticsearch side. It is automatically created when the tileindex is setup and removed during teardown.
This change seems to significant increase performance and speed while indexing files (see #45 for details). I have tested the changes with the CLI tool for entire model runs (`geomet-data-registry data add -d <model_run>` and the result are consistent.
We'll have to test this with a live AMQP feed next.

Add ES ingest pipeline to calculate file registration time on ES side

---

geomet_data_registry/layer/model_gem_global.py

Fixes #48.
In situations where no time interval is defined for a given GDPS layer (PT0H), the `layers/model_gem_global.py` layer handler would error out due to the `range` function being called with a a step of 0 (see [L114](https://github.com/ECCC-MSC/geomet-data-registry/compare/master...Dukestep:gdps-pt0h-interval-fix?expand=1#diff-5770a3fccda74a8fe7a62c1ef12135cbL114)).
Tested problematic layers with geomet-data-registry CLI tool to confirm the fix.
cc @RousseauLambertLP

Added handling for when interval is PT0H

---

geomet_data_registry/handler/core.py
geomet_data_registry/layer/base.py
geomet_data_registry/layer/cansips.py
geomet_data_registry/layer/model_gem_global.py
geomet_data_registry/layer/radar_1km.py
geomet_data_registry/layer/reps.py
geomet_data_registry/tileindex/elasticsearch_.py
geomet_data_registry/util.py

Fixes #49.
Changes to format the `file_creation_datetime`, `reference_datetime` and `forecast_hour_datetime` properties in the various Layer objects (i.e. RepsLayer, ModelGemGlobalLayer)  in UTC ISO 8601 datetime string with the 'Z' designator.
This fix also applies to all the the the various "management" datetime objects such as `received_datetime` and `identify_datetime`.
Using these formats also allows to more strictly define the expected datetime format for each property in the ES mapping for the geomet-data-registry index.

Added Zulu designator 'Z' to all datetimes and modified ES mapping to expect this format

---

geomet_data_registry/layer/base.py

added error log when we have an incomplete model run
Loge example:
`[2019-11-05T14:25:01Z] ERROR - Incomplete model run: 12Z --> 3 / 81 files (GDPS.ETA_TT)`

added error log when we have an incomplete model run

---

geomet_data_registry/handler/__init__.py
geomet_data_registry/handler/core.py
geomet_data_registry/layer/base.py
geomet_data_registry/layer/radar_1km.py
geomet_data_registry/util.py

added time keyword for radar in store
For radar we have default time and time extent in redis like:
```
127.0.0.1:6379> GET RADAR_1KM_RSNO_default_time
"2019-11-12T15:20:00Z"
127.0.0.1:6379> GET RADAR_1KM_RSNO_time_extent
"2019-11-12T12:20:00Z/2019-11-12T15:20:00Z/PT10M"
```
These can then be used in a mapfile directly and used for logging errors like missing timestep

added time keyword for radar in store

---

geomet_data_registry/layer/base.py
geomet_data_registry/layer/cansips.py
geomet_data_registry/layer/model_gem_global.py
geomet_data_registry/layer/radar_1km.py
geomet_data_registry/layer/reps.py
geomet_data_registry/util.py

add time keys for NWP models
And yes I forgot but we need the `self.new_key_store = False` because I'm using that key in the handler script to trigger the writting of the time keywords in Redis whenever a model run is complete, or when a new radar file is added. This is done in the count function of the layer/base.py script.

add time keys for NWP models

---

geomet_data_registry/handler/core.py
geomet_data_registry/layer/model_hrdps_continental.py
geomet_data_registry/plugin.py

Initial HRDPS Continental layer handler. Tested and verified using the CLI tool with data retrieved from the DataMart via wget.
Also, if a file is passed to the GDPS or HRDPS handler and its forecast hour is not included in the variable's `forecast_hour` key in the respective yaml configuration, the identify method now returns False and will not try to register the layer into geomet-data-registry.
Minor PEP8 fixes also included.

initial hrdps layer handler and fixes for gdps handler

---

geomet_data_registry/layer/radar_1km.py
geomet_data_registry/store/redis_.py

This MR adds the `decode_responses=True` keyword argument to the Redis store connection, enabling all responses from Redis to be returned as strings instead of bytes.
I have also removed any `.decode()` calls for any instance where we were decoding bytes when getting keys from the Redis store.

set redis to decode responses to strings

---

geomet_data_registry/handler/__init__.py

This PR fixes an issue where data was not sorted properly when using the CLI `geomet-data-registry data add -d` functionality resulting in older model runs overwriting the `default_model_run` value of the newest model run available in the passed directory.
The approach taken now is to create a complete list of files prior to doing any sorting. Once the list of files is final,  the complete list is sorted by the `mtime` of the file, which is the time the file was initially created.

fixed sorting when adding data directory via CLI

---

geomet_data_registry/store/__init__.py

This PR adds a try/except condition when retrieving a key from the store via the CLI. The `geomet-data-registry get -k [key_name]` CLI command was failing when trying to retrieve a key's value that did not contain JSON.

add try/except for store get key value echoing in CLI

---

conf/geps.yml
conf/sarracenia/geps.conf
geomet_data_registry/handler/core.py
geomet_data_registry/layer/geps.py
geomet_data_registry/plugin.py

Adds the inital Global Ensemble Prediction System (GEPS) yml configuration, sarracenia config and layer handler.
The YAML only currently includes GEPS products and not the raw data (i.e member data). This will be done at a later date.
Validated with complete model runs pulled from DD.

initial configuration for GEPS

---

conf/model_gem_global.yml
geomet_data_registry/layer/base.py
geomet_data_registry/layer/model_gem_global.py
geomet_data_registry/layer/model_gem_regional.py
geomet_data_registry/layer/model_hrdps_continental.py

This MR fixes an issue when a variable was producing an empty list of items (meaning a variable is defined in the model configuration but the forecast hour is not used by GeoMet).
Also contained in this MR are changes to the GDPS configuration (recent unannounced changes on DD change the number of files available for certain variables!).

fix gdps, hrdps, rdps empty returning empty items list, gdps conf

---

geomet_data_registry/layer/geps.py

Use the new `vrt://` URI for on-the-fly VRT creation for GEPS layer handler.
Also, minor PEP 8 fixes.

change VRT referencing to new vrt:// method

---

geomet_data_registry/layer/cgsl.py
geomet_data_registry/layer/geps.py
geomet_data_registry/layer/model_gem_global.py
geomet_data_registry/layer/model_gem_regional.py
geomet_data_registry/layer/model_giops.py
geomet_data_registry/layer/model_hrdps_continental.py
geomet_data_registry/layer/reps.py

Small PR to catch instances where, if an older complete model run was added via the CLI, the time keys would be updated and replace those of the most recent model run using the older datetimes.
Technically, this should never happen via AMQP but could happen via the CLI when, for example, we decide to load a model run a previous model run manually in case of a failure with AMQP.

improve time key adding logic

---

conf/model_gem_global.yml
geomet_data_registry/layer/base.py
geomet_data_registry/layer/model_gem_global.py
geomet_data_registry/tileindex/elasticsearch_.py
geomet_data_registry/util.py

This PR contains an implementation for managing GeoMet GDPS layers that require having two or more variables in the registry before creating the tileindex record for the given layer.
Steps taken to enable this functionality:
1. Modified the `model_gem_global.yml` configuration file to add a `dependencies` key that contains the name of the GeoMet layer on which the variable depends on. Also added a `bands_order` key that specifies the order in which the bands need to be created within the VRT. For example:
```yaml
UGRD_ISBL_1000:
[...]
geomet_layers:
GDPS.PRES_UGRD.1000:
forecast_hours: 000/240/PT3H
GDPS.PRES_UU.1000:
dependencies:
- GDPS.PRES_VGRD.1000
forecast_hours: 000/240/PT3H
bands_order:
- UGRD_ISBL
- VGRD_ISBL
```
2. When `model_gem_global.py` encounters a layer with dependencies, …

Initial GDPS UU layers implementation

---

geomet_data_registry/event.py
geomet_data_registry/handler/base.py
geomet_data_registry/layer/base.py
geomet_data_registry/store/base.py
geomet_data_registry/tileindex/base.py

Removes redundant `object` parameter from class definitions throughout the codebase.
See https://docs.python.org/2/reference/datamodel.html#new-style-and-classic-classes for details regarding this change. By default, Python 3 only creates new style classes regardless of if the `object` parameter is passed or not.

change class definitions to new style

---

conf/model_giops.yml
geomet_data_registry/layer/base.py
geomet_data_registry/layer/cgsl.py
geomet_data_registry/layer/geps.py
geomet_data_registry/layer/model_gem_global.py
geomet_data_registry/layer/model_gem_regional.py
geomet_data_registry/layer/model_giops.py
geomet_data_registry/layer/model_hrdps_continental.py
geomet_data_registry/layer/radar_1km.py
geomet_data_registry/layer/reps.py
geomet_data_registry/util.py

This pull requests moves the `add_time_key()` method implemented by each model into the `BaseLayer` class in order to avoid some repetition in our code. The radar handler overwrites the method due to it's own particular characteristics (e.g. no model runs).
Tested these changes with complete model run data for all layer handlers that are affected.
Also included in this PR:
- Minor changes to `VRTDataset` util class (changed logger debug messages and add r to string literal for regex).
- Created `is_valid_interval()` static method in BaseLayer used by many model handlers to check if the incoming file is a valid time step as per the forecast_hours defined for that variable in its respective configuration file.
- Removal of some double quotes and other flake8 issues.
- Minor configuration …

refactor and move add_time_key method to BaseLayer class

---

conf/cgsl.yml
conf/model_gem_regional.yml
conf/model_giops.yml
conf/model_hrdps_continental.yml
geomet_data_registry/layer/model_gem_regional.py
geomet_data_registry/layer/model_giops.py
geomet_data_registry/layer/model_hrdps_continental.py

Add UU layer handling in HRDPS, GIOPS and RDPS layer handlers and added these new layers to the yaml configuration file for each model.
From what I can tell, we now have all UU layers in GeoMet 2 being served via GeoMet 3.
I have tested each model with complete model runs for the impacted variables.

add UU layer handling for HRDPS, GIOPS, RDPS

---

geomet_data_registry/event.py
geomet_data_registry/handler/base.py
geomet_data_registry/handler/core.py
geomet_data_registry/layer/base.py
geomet_data_registry/layer/cansips.py
geomet_data_registry/layer/cgsl.py
geomet_data_registry/layer/gdwps.py
geomet_data_registry/layer/geps.py
geomet_data_registry/layer/hrdpa.py
geomet_data_registry/layer/model_gem_global.py
geomet_data_registry/layer/model_gem_regional.py
geomet_data_registry/layer/model_giops.py
geomet_data_registry/layer/model_hrdps_continental.py
geomet_data_registry/layer/radar_1km.py
geomet_data_registry/layer/rdpa.py
geomet_data_registry/layer/rdwps.py
geomet_data_registry/layer/reps.py
geomet_data_registry/layer/wcps.py
geomet_data_registry/store/redis_.py
geomet_data_registry/tileindex/elasticsearch_.py

This PR adds an optional URL property to handling workflow so that GDR can manage a tileindex of remote files (which, in our case, can be downloaded on demand based on user-driven requests).
In addition, minor changes to ABC workflow (-> `super().`)

add URL property to workflow

---

geomet_data_registry/layer/base.py
geomet_data_registry/layer/gdwps.py
geomet_data_registry/layer/model_gem_global.py
geomet_data_registry/layer/model_gem_regional.py
geomet_data_registry/layer/model_giops.py
geomet_data_registry/layer/model_hrdps_continental.py
geomet_data_registry/layer/rdwps.py
geomet_data_registry/layer/wcps.py

This PR changes indexed documents weather_variable and url properties into arrays and implements multiple url entries for tileindex documents that are composed of two or more weather variables.
See the GDPS.ETA_UU example below.
```json
"properties":{
"elevation":"surface",
"identifier":"GDPS.ETA_UU-20200305000000-20200305210000",
"reference_datetime":"2020-03-05T00:00:00Z",
"forecast_hour_datetime":"2020-03-05T21:00:00Z",
"identify_datetime":"2020-07-02T13:35:01.607538Z",
"weather_variable":[
"VGRD_TGL_10",
"UGRD_TGL_10"
],
"layer":"GDPS.ETA_UU",
"url":[
"foo",
"bar"
],
"file_creation_datetime":"2020-03-05T04:19:07.000000Z",
"filepath":"foo",
"member":null,
"model":"model_gem_global",
"receive_datetime":"2020-07-02T13:35:01.585698Z",
"register_datetime":"2020-07-02T13:35:01.609918Z"
}
} …
```

Make tileindex url and weather_variable properties arrays

---

geomet_data_registry/layer/cansips.py
geomet_data_registry/store/__init__.py
geomet_data_registry/store/redis_.py
geomet_data_registry/util.py

Adds the `geomet-data-registry_` prefix to all keys written to a store.
The prefix is also added to all `store.get_key()` calls.
`geomet-data-registry store list` lists the keys without the prefix, while a `geomet-data-registry get -k <name>` automatically adds the prefix.

use `geomet-data-registry_` prefix on store keys

---

geomet_data_registry/store/__init__.py
geomet_data_registry/store/redis_.py

Adds a `--raw` or `-r` flag to the `geomet-data-registry store [list, get, set]` commands and improves the `click` echoes to show the exact key requested from the store.
For example:
```bash
geomet-data-registry store list -r # show keys with their geomet-data-registry_ prefix
geomet-data-registry store get -r -k geomet-data-registry_GDPS.ETA_TT_model_run_extent # retrieves the key without adding the geomet-data-registry_ prefix
```

add --raw flag to store CLI command

---

geomet_data_registry/tileindex/base.py
geomet_data_registry/tileindex/elasticsearch_.py

Adds a generic TileNotFoundError to `tileindex/base.py` and implements it in ElasticsearchTileIndex.get() method.

Add a TileNotFoundError

---

geomet_data_registry/layer/radar_1km.py

Adds a `layer_config` key  to feature_dicts generated by `Radar1kmLayer.identify()`.
General code refactoring also included.

refactor and add layer_config in radar layer handler feature_dict

---

deploy/default/sarracenia/radar.conf
geomet_data_registry/layer/base.py
geomet_data_registry/layer/model_hrdps_continental.py

Bug fixes:
* Avoid raising `NoTileFoundError` when checking for layer dependencies by using a `try/except` block, and returning False if dependencies are not found.
* Remove additional `.` character in `deploy/default/sarracenia/radar.conf`.
* Add missing url param to `super.identify()` call in `ModelHrdpsContinentalLayer.identify()`, which was causing HRDPS ES documents to have a missing url item.

Small bug fixes

---

geomet_data_registry/handler/core.py
geomet_data_registry/plugin.py

This merge request aims to improve the way we define plugin definitions, and the way we handle identifying received filepaths from AMQP notifications.
In regards to the layer plugins, this MR merges the information previously held in the `DATASET_HANDLERS` dict in `geomet_data_registry/handler/core.py`  into the actual plugin definition itself (see the `pattern` key for layer-type plugins in `geomet_data_registry/plugin.py`). The `pattern` key is now a  unix shell-style pattern (with wildcard support), allowing us much more flexibility in the way we associate a layer plugin to an incoming filepath. Using the `fnmatch` standard library, we can then match the pattern to the filepath's basename. This improves on the previous method where we only checked if a substring was found in the entire …

refactor plugin definitions

---

geomet_data_registry/layer/model_raqdps-fw-ce.py
geomet_data_registry/layer/model_rdaqa-ce.py

Fixes an issue where a cumulative effects layer would not have its default_time key value updated when a more recent file was handled.

ensure default time is updated for cumulative effects loaders

---

geomet_data_registry/notifier/base.py
geomet_data_registry/notifier/celery_.py

Ensures that a connection to the Celery broker can be made when instantiating a CeleryTaskNotifier object. Works for both `redis://localhost:6379` and `amqp://localhost:5672` URI schemes.

Ensure broker connection can be established upon CeleryTaskNotifier instantiation

---

deploy/default/model_gem_regional.yml
deploy/default/model_giops.yml
deploy/default/model_riops.yml
deploy/default/sarracenia/model_riops.conf
geomet_data_registry/layer/model_gem_regional.py
geomet_data_registry/layer/model_riops.py
geomet_data_registry/plugin.py

This MR contains the initial RIOPS layer handler and configuration.
It also contains the following model fixes/improvements:
- Modifies  `deploy/default/model_gem_regional.yml`  and `geomet_data_registry/layer/model_gem_regional.py` now that RDPS forecast hours now cover [84 hours for all model runs](https://lists.ec.gc.ca/pipermail/dd_info/2020-September/000412.html).
- Fixed typos in dependency names for `OCEAN.GIOPS.3D_UU2W_<depth>` layers in `deploy/default/model_giops.yml`.
- When iterating over bands, ensure a `deepcopy` of `weather_var['geomet_layers']` is made in order to avoid continuously modifying the same object in memory when iterating over each band in the GIOPS/RIOPS layer handlers.

RIOPS initial loader and config and misc model fixes

---

geomet_data_registry/layer/base.py

Remove unused argument (item_dict) in the update count function. This function is only called in the base.py script for layers.
The update_count function is only called in the base.py script in the layer folder.

removed unused argument item_dict from function input

---

geomet_data_registry/store/redis_.py

When installing GDR via docker (which automatically pulls the latest redis-py version `4.0.0rc1`, I was hit with an unexpected keyword argument error.
The `charset` keyword argument will be  removed in newer versions of redis-py. It is suggested to use the `encoding` keyword argument that already has a default value of  `utf-8`. See redis-py's [`redis.Connection()`](https://redis-py.readthedocs.io/en/stable/#redis.Connection) documentation for further details.
I have tested this change against redis-py `3.5.3` and `4.0.0rc1`, it will allow for a smoother transition down the line.

remove redis-py deprecated charset argument

---

geomet_data_registry/layer/model_raqdps.py

Removes an unnecessary dependencies check for RAQDPS layers since no RAQDPS weather variables have dependencies.
Thanks @PhilippeTH for the heads up.

remove unnecessary RAQDPS dependencies check

---

deploy/default/reps.yml

Removes REPS layers at 10mb for `PRES_TT.10`, `PRES_HR.10`, `PRES_GZ.10` since these variables are no longer operationally produced at this pressure level.

remove REPS layers at 10mb
